<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Go to Amazon Shopping</name>
   <tag></tag>
   <elementGuidId>691ff958-17b2-45ff-ad9f-2f789b10a63f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.Button_button__PjVhE.Button_primary___XGO6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Go to Amazon Shopping&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5084f487-acdc-4c26-b652-413b01d65d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b6cb6325-70d6-4180-84bd-a362b970f633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> Button_button__PjVhE Button_primary___XGO6</value>
      <webElementGuid>05411d0c-0ad8-4d74-aed9-9eb3fd3219e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go to Amazon Shopping</value>
      <webElementGuid>9f2c9688-e6b8-4688-ad6f-9c4e61bc83cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;CriticalError_container__wmb3h&quot;]/div[@class=&quot;CriticalError_errorContent__c8izx&quot;]/button[@class=&quot;Button_button__PjVhE Button_primary___XGO6&quot;]</value>
      <webElementGuid>6d6b9c5f-3b0b-4db9-acaa-286f5a62d728</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>2e336a30-3f74-4c8d-bff1-8ec11dd5f47c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/button</value>
      <webElementGuid>e2a18f2f-09aa-4a23-aa0f-142bf61fddf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video unavailable in your location'])[1]/following::button[1]</value>
      <webElementGuid>1e73454e-dd44-4aec-8093-14ee1ac7b8ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Go to Amazon Shopping']/parent::*</value>
      <webElementGuid>81738c33-166f-4861-93aa-90557e7bc9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>57001304-5e4b-4c32-a559-d62e8aa0fdec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Go to Amazon Shopping' or . = 'Go to Amazon Shopping')]</value>
      <webElementGuid>a4f711af-0ef1-4bf0-97db-6c6331ebc5ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
